/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-05-18 01:18:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.MemberDTO;
import member.MemberDAO;

public final class userInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.MemberDAO");
    _jspx_imports_classes.add("member.MemberDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>member/userInfo.jsp</title>\r\n");
      out.write("<link href=\"../css/default.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"../css/subpage.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");



String id = (String)session.getAttribute("id");

out.print(id);

MemberDAO memberDAO = new MemberDAO();
MemberDTO memberDTO = memberDAO.getMember(id);
// MemberDTO memberDTOR = memberDAO.getRating(memberDTO.getRating());



      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("<!-- 헤더들어가는 곳 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/top.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- 헤더들어가는 곳 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 본문들어가는 곳 -->\r\n");
      out.write("<!-- 본문메인이미지 -->\r\n");
      out.write("<div id=\"sub_img_member\"></div>\r\n");
      out.write("<!-- 본문메인이미지 -->\r\n");
      out.write("<!-- 왼쪽메뉴 -->\r\n");
      out.write("<nav id=\"sub_menu\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li><a href=\"#\">Join us</a></li>\r\n");
      out.write("<li><a href=\"#\">Privacy policy</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- 왼쪽메뉴 -->\r\n");
      out.write("<!-- 본문내용 -->\r\n");
      out.write("<article>\r\n");
      out.write("<h1>회원정보</h1>\r\n");
      out.write("<form action=\"update.jsp\" name=\"fr\" id=\"join\" method=\"post\" onsubmit=\"return fn_Checkpass();\">\r\n");
      out.write("<fieldset>\r\n");
      out.write("<legend>기본정보</legend>\r\n");
      out.write("<label>ID</label><div id=\"duplicateId\"></div>\r\n");
      out.write("<input type=\"text\" name=\"id\"  value=\"");
      out.print(memberDTO.getId());
      out.write("\"readonly ><br>\r\n");
      out.write("<label>이름</label>\r\n");
      out.write("<input type=\"text\" name=\"name\" value=\"");
      out.print(memberDTO.getName());
      out.write("\" readonly><br>\r\n");
      out.write("<label>E-Mail</label>\r\n");
      out.write("<input type=\"email\" name=\"email\" value=\"");
      out.print(memberDTO.getEmail());
      out.write("\" readonly><br>\r\n");
      out.write("<label>총 누적한 포인트</label>\r\n");
      out.write("<input type=\"text\" name=\"point\" value=\"");
      out.print(memberDTO.getPoint_max());
      out.write("\" readonly><br>\r\n");
      out.write("<label>사용가능 포인트</label>\r\n");
      out.write("<input type=\"text\" name=\"point\" value=\"");
      out.print(memberDTO.getPoint_cur());
      out.write("\" readonly><br>\r\n");
      out.write("<label>회원등급</label>\r\n");
      out.write("<input type=\"text\" name=\"rating\" value=\"");
      out.print(memberDTO.getRating_name());
      out.write("\" readonly><br>\r\n");
      out.write("\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<legend>추가정보</legend>\r\n");
      out.write("<label>주소</label>\r\n");
      out.write("<input type=\"text\" name=\"address\" id=\"addr1\" value=\"");
      out.print(memberDTO.getAddress());
      out.write("\" readonly><br>\r\n");
      out.write("\r\n");
      out.write("<label>집전화</label>\r\n");
      out.write("<input type=\"text\" name=\"phone\" value=\"");
      out.print(memberDTO.getPhone());
      out.write("\" readonly><br>\r\n");
      out.write("<label>개인번호</label>\r\n");
      out.write("<input type=\"text\" name=\"mobile\" value=\"");
      out.print(memberDTO.getMobile());
      out.write("\" readonly><br>\r\n");
      out.write("</fieldset>\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<div id=\"buttons\">\r\n");
      out.write("<input type=\"submit\" value=\"회원정보 수정\" class=\"submit\" style=\"cursor: pointer;\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</article>\r\n");
      out.write("<!-- 본문내용 -->\r\n");
      out.write("<!-- 본문들어가는 곳 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<!-- 푸터들어가는 곳 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/bottom.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- 푸터들어가는 곳 -->\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
